### ISSUE TITLE
Acc remain 0.42 after 3 epochs

### ISSUE THREAD

**Issue by Wemmy** [jhcknzzm/SSFL-Benchmarking-Semi-supervised-Federated-Learning#1]
Hello, thank you for your brilliant work!
I tried to reproduce the experiement number 0 with cifar-10, but the acc results in 13.98, 17.35, 13.15, 0.42, 0.42, 0.42...
I am using compute cluster of one node with 4 gpus. Besides IP address and gpulist, I changed SynAllreduce function by communicate param instead of param.data as mentioned 
[https://discuss.pytorch.org/t/api-change-for-tensor-data-set-in-torch-nightly/33310/3](url).
Do you have any idea of this error?

**Comment by jhcknzzm** [comment]
Hi, can you use PyTorch 1.0.0 and torchvision 0.2.2 ? I haven't tried torch nightly. Maybe this error is caused by inconsistent versions of pytorch. On the machine I used, the acc is 31.22, 34.23, 35.42, 33.18, 42.85, 37.35, ....

**Comment by Wemmy** [comment]
> Hi, can you use PyTorch 1.0.0 and torchvision 0.2.2 ? I haven't tried torch nightly. Maybe this error is caused by inconsistent versions of pytorch. On the machine I used, the acc is 31.22, 34.23, 35.42, 33.18, 42.85, 37.35, ....

I also tried with PyTorch 1.0.0 and torchvision 0.2.2. Same issue happened. The wierd thing is that the acc drops to 0.42 on exact forth epoch. I guess it may be something with hardware configuration?
