### ISSUE TITLE
Hello, could you please disclose the processing of COVID-19 dataset? Thank you!

### ISSUE THREAD

**Issue by fengyann** [jhcknzzm/SSFL-Benchmarking-Semi-supervised-Federated-Learning#3]
Hello, could you please disclose the processing of COVID-19 dataset? Thank you!

**Comment by jhcknzzm** [comment]
The COVID-19 dataset is worth studying. But we have not done experiments on this dataset. We think the recent paper _arXiv:2011.11750_,  seems to be worthy of reference.  As for the processing of COVID-19 dataset, we think, first one need write a class to read this dataset like _torchvision.datasets.CIFAR10_, then one can define a function like get_cifar10() in our code (in the dataset folder) to create different dataloaders for different users. One can also define a function like _getNonIIDdata()_ in our utils_v2.py to distribute data index to different users.  When the above things are all done, you can call the written function to load the dataset in the train_LocalSGD.py (for example, _get_cifar10()_), and assign the dataloader to each user for training.

**Comment by jhcknzzm** [comment]
> Hello, could you please disclose the processing of COVID-19 dataset? Thank you!

The COVID-19 dataset is worth studying. But we have not done experiments on this dataset. We think the recent paper _arXiv:2011.11750_,  seems to be worthy of reference.  As for the processing of the COVID-19 dataset, we think, first, one needs to write a class to read this dataset like _torchvision.datasets.CIFAR10_, then one can define a function like get_cifar10() in our code (in the dataset folder) to create different dataloaders for different users. One can also define a function like _getNonIIDdata()_ in our utils_v2.py to distribute data index to different users.  When the above things are all done, you can call the written function to load the dataset in the train_LocalSGD.py (for example, _get_cifar10()_), and assign the dataloader to each user for training.
